[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spy-fairness-tests"
version = "1.0.0"
description = "Core algorithms for testing spy selection fairness"
readme = "README.md"
license = {file = "../../LICENSE"}
requires-python = ">=3.9"
authors = [
    {name = "Advay Chandorkar", email = "advay@example.com"},
]
maintainers = [
    {name = "Advay Chandorkar", email = "advay@example.com"},
]
keywords = ["fairness", "algorithms", "testing", "spy-game", "statistics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Testing",
    "Topic :: Scientific/Engineering :: Mathematics",
]

dependencies = [
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "matplotlib>=3.5.0",
    "pandas>=1.3.0",
]

[project.urls]
Homepage = "https://github.com/advayc/spy-test"
Repository = "https://github.com/advayc/spy-test.git"
Issues = "https://github.com/advayc/spy-test/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["spy_fairness_tests*"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --cov=spy_fairness_tests --cov-report=html --cov-report=term-missing"
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"